如果您希望在 Node.js 应用程序中操作阿里云 OSS，以实现文件的上传、下载、存储和管理，可以参考本文安装 OSS Node.js SDK。

## **环境准备**

-   环境要求
    
    -   推荐使用Node.js 8.0及以上版本。
        
    -   请参考[Node.js安装](https://nodejs.org/zh-cn/download/package-manager)下载和安装编译运行环境。
        
-   查看语言版本
    
    -   执行以下命令查看Node.js版本。
        
        ```
        node -v
        ```
        
    -   执行以下命令查看npm版本。
        
        ```
        npm -v
        ```
        

## **安装SDK**

-   SDK版本选择
    
    -   如果您使用的是Node.js 8.0及以上版本，请使用官网最新SDK 6.x版本。
        
    -   如果您使用的是Node.js 8.0以下版本，请使用SDK 4.x版本.
        
-   执行以下命令安装SDK
    
    -   安装SDK 6.x版本
        
        ```
        npm install ali-oss@^6.x --save
        ```
        
    -   安装SDK 4.x版本
        
        ```
        npm install ali-oss@^4.x --save
        ```
        

## **验证SDK**

您可以使用以下命令来验证`ali-oss`是否安装成功并查看其版本。

```
npm list ali-oss
```

成功返回示例如下，以下示例表明您已经成功安装`ali-oss`。

```
your-project-name@ /path/to/your/project
└── ali-oss@6.x.x
```

## **后续步骤**

安装SDK后，您需要配置访问凭证。详情请参见[配置访问凭证（Node.js SDK）](https://help.aliyun.com/zh/oss/node-js-configure-access-credentials)。